# Generated by Django 3.2.13 on 2023-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0007_rawleveldata_urlparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=128, unique=True)),
                ('rawData', models.JSONField(blank=True, null=True)),
                ('registeredComplete', models.JSONField(blank=True, default=False)),
                ('urlParameters', models.JSONField(blank=True, null=True)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('cohortYear', models.CharField(blank=True, max_length=64)),
                ('isStaff', models.BooleanField(default=False)),
            ],
        ),
    ]
