# Generated by Django 3.2.13 on 2023-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0008_risedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risedata',
            name='registeredComplete',
            field=models.JSONField(blank=True),
        ),
    ]
