# Generated by Django 3.2.13 on 2023-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0009_alter_risedata_registeredcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risedata',
            name='rawData',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='risedata',
            name='registeredComplete',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='risedata',
            name='urlParameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
