# Generated by Django 3.2.13 on 2023-09-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0010_auto_20230918_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='risedata',
            name='environment',
            field=models.CharField(choices=[('staging', 'staging'), ('production', 'production'), ('other', 'other')], default='production', max_length=16),
        ),
        migrations.AlterField(
            model_name='risedata',
            name='registeredComplete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
