# Generated by Django 3.2.13 on 2023-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0011_auto_20230919_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layoutId', models.CharField(max_length=64, unique=True)),
                ('layout', models.CharField(max_length=1024)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
            },
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=256, unique=True)),
                ('iv', models.CharField(max_length=256, null=True)),
                ('tag', models.CharField(max_length=256, null=True)),
                ('data', models.CharField(default='[]', max_length=16384)),
                ('gameParameters', models.CharField(default='[]', max_length=16384)),
                ('riseTracking', models.CharField(default='[]', max_length=16384)),
                ('registeredComplete', models.BooleanField(default=False)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('cohortYear', models.CharField(blank=True, max_length=64)),
                ('isStaff', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('staging', 'staging'), ('production', 'production'), ('other', 'other')], default='production', max_length=16)),
            ],
            options={
                'verbose_name': 'PlayerData',
                'verbose_name_plural': 'PlayerData',
            },
        ),
    ]
