# Generated by Django 3.2.13 on 2023-10-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effugium', '0012_config_playerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='layout',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='gameParameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='riseTracking',
            field=models.JSONField(default=dict),
        ),
    ]
