# Generated by Django 3.2.13 on 2023-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelconfig',
            name='startScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelconfig',
            name='targetScore',
            field=models.IntegerField(default=0),
        ),
    ]
