# Generated by Django 3.2.13 on 2023-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0003_levelconfig_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptLevel', models.IntegerField()),
                ('strategyLevel', models.IntegerField()),
                ('target', models.CharField(max_length=512)),
                ('distractorA', models.CharField(max_length=512)),
                ('distractorB', models.CharField(max_length=512)),
                ('start', models.CharField(max_length=512)),
                ('end', models.CharField(max_length=512)),
                ('scores', models.CharField(max_length=512)),
            ],
        ),
    ]
