# Generated by Django 3.2.13 on 2023-08-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0004_graphs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=256)),
                ('RawData', models.JSONField()),
                ('IP', models.CharField(blank=True, max_length=64)),
                ('Metadata', models.JSONField()),
            ],
        ),
    ]
