# Generated by Django 3.2.13 on 2023-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0008_alter_player_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
