# Generated by Django 3.2.13 on 2023-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0009_alter_player_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenID', models.IntegerField(unique=True)),
                ('conceptLevel', models.IntegerField()),
                ('strategyLevel', models.IntegerField()),
                ('targetScore', models.IntegerField()),
                ('target', models.CharField(max_length=512)),
                ('distractorA', models.CharField(max_length=512)),
                ('distractorB', models.CharField(max_length=512)),
                ('start', models.CharField(max_length=512)),
                ('end', models.CharField(max_length=512)),
                ('scores', models.CharField(max_length=512)),
                ('notes', models.TextField(max_length=4096)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='givenID',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
