# Generated by Django 3.2.13 on 2023-08-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0011_alter_graphdesign_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphdesign',
            old_name='givenID',
            new_name='givenName',
        ),
    ]
