# Generated by Django 3.2.13 on 2023-08-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0013_auto_20230810_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphs',
            options={'verbose_name': 'Graphs', 'verbose_name_plural': 'Graphs'},
        ),
    ]
