# Generated by Django 3.2.13 on 2023-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0016_auto_20230920_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='level',
            new_name='curriculumLevel',
        ),
        migrations.AddField(
            model_name='graphs',
            name='difficultyLevel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
