# Generated by Django 3.2.13 on 2023-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0017_auto_20231001_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdesign',
            name='nodes',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='graphdesign',
            name='scores',
            field=models.CharField(max_length=4096),
        ),
    ]
