# Generated by Django 4.0.4 on 2023-10-05 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0020_alter_pointerplayer_rawdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointerplayer',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pointerplayer',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
