# Generated by Django 3.2.13 on 2023-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0021_pointerplayer_lastmodified_pointerplayer_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointerplayer',
            name='RawData',
            field=models.CharField(blank=True, max_length=4194304, null=True),
        ),
    ]
