# Generated by Django 3.2.13 on 2023-10-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0023_pointerplayer_platformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointerplayer',
            name='Metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pointerplayer',
            name='platformData',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
