# Generated by Django 3.2.13 on 2023-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0024_auto_20231005_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointerplayer',
            name='RawData',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
