# Generated by Django 3.2.13 on 2023-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0025_alter_pointerplayer_rawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointerplayer',
            name='RawData',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
